language: c
sudo: false
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libc6-dev
      - libevent-dev
      - libfontconfig1-dev
      - libsdl2-dev
      - libsdl2-ttf-dev

matrix:
  include:
    addons:
      apt:
        packages:
          - gcc-6
    compiler:
      - gcc
    env:
      - MATRIX_EVAL="CC=gcc-6"

cache:
  apt: true

compiler:
  - clang
  - gcc

git:
  depth: 1

os:
  - linux

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
