language: c
sudo: false
dist: xenial

addons:
  apt:
    packages:
      - cmake
      - libc6-dev
      - libevent-dev
      - libfontconfig1-dev
      - libsdl2-dev
      - libsdl2-ttf-dev

matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env:
        - MATRIX_EVAL="CC=gcc-6"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
      env:
        - MATRIX_EVAL="CC=gcc-8"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
      env:
        - MATRIX_EVAL="CC=gcc-9"

cache:
  apt: true

git:
  depth: 1

os:
  - linux

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
