language: c
sudo: false
dist: xenial

addons:
  apt:
    packages:
      - cmake
      - libevent-dev
      - libfontconfig1-dev
      - libsdl2-dev
      - libsdl2-ttf-dev

cache:
  apt: true

compiler:
  - clang
  - gcc

git:
  depth: 1

os:
  - linux

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
